name: 'Rsync Deployments Action with password'
description: 'GitHub Action for deploying code via rsync over ssh to hosts that require passwords'
author: 'spslater'
inputs:
  switches:
    description: 'The switches'
    required: true
  rsh:
    description: 'The remote shell argument'
    required: false
    default: ''
  path:
    description: 'The local path'
    required: false
    default: ''
  remote_path:
    description: 'The remote path'
    required: true
  remote_host:
    description: 'The remote host'
    required: true
  remote_port:
    description: 'The remote port'
    required: false
    default: 22
  remote_user:
    description: 'The remote user'
    required: true
  remote_password:
    description: The remote password'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'folder-plus'  
  color: 'gray-dark'
